<?php
/**
* TinyConfig
*
* File: icms_version.php
*
* @copyright	http://www.xoops.org/ The XOOPS Project
* @copyright	XOOPS_copyrights.txt
* @copyright	http://www.impresscms.org/ The ImpressCMS Project
* @license		GNU General Public License (GPL)
*				a copy of the GNU license is enclosed.
* ----------------------------------------------------------------------------------------------------------
* 				TinyConfig
* @since		1.00
* @author		McDonald
* @version		$Id$
*/

if ( !defined( 'ICMS_ROOT_PATH' ) ) die( 'ICMS root path not defined' );

global $icmsConfig;

// ** General information
$modversion = array(
	'name'				=> 'TinyConfig',
	'version'			=> 2.0,
	'status'			=> 'Final',
	'status_version'	=> 'Final',
	'date'				=> '18 September 2012',

	'description'		=> _MI_TINYCFG_DESCRIPTION,
	'author'			=> 'McDonald',
	'credits'			=> 'Moxiecode Systems AB (TinyMCE), frankblack (TinyEditor author)',
	'license'			=> 'GNU General Public License (GPL)',
	'image'				=> 'images/tinycfg.png',
	'iconbig'			=> 'images/tinycfg_big.png',
	'iconsmall'			=> 'images/tinycfg_small.png',
	'dirname'			=> basename( dirname( __FILE__ ) ),
	'modname'			=> 'tinyconfig'
);

// ** Contributors **
$modversion['people']['developers'] []	= '<a href="http://community.impresscms.org/userinfo.php?uid=179" target="_blank">McDonald</a>';

$modversion['people']['other'][]		= '&middot; <a href="http://www.tinymce.com/" target="_blank">Moxiecode Systems AB</a> (TinyMCE, icon & text tooltips)';
$modversion['people']['other'][]		= '&middot; <a href="http://lytebox.com" target="_blank">Lytebox</a>';

$modversion['people']['translators'][]	= '&middot; <a href="http://community.impresscms.org/userinfo.php?uid=97" target="_blank">debianus</a> (Spanish)';
$modversion['people']['translators'][]	= '&middot; <a href="http://community.impresscms.org/userinfo.php?uid=179" target="_blank">McDonald</a>  (Dutch)';

$modversion['manual']['wiki'][] = '<a href="http://www.tinymce.com/wiki.php/Configuration" target="_blank">TinyMCE Configuration</a>';

$modversion['warning'] = _CO_ICMS_WARNING_BETA;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'tinycfg_configs';
$modversion['tables'][1] = 'tinycfg_toolsets';
$modversion['tables'][2] = 'tinycfg_simpletoolset';

// Launch additional install script
$modversion['onInstall'] = '';
$modversion['onUpdate']  = 'admin/update.php';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu']  = 'admin/menu.php';

// Search
$modversion['hasSearch'] = 0;

// Menu
$modversion['hasMain'] = 0;

?>